### ISSUE TITLE
Cleanup Makefile

### ISSUE THREAD

**Issue by kylebrandt** [grafana/gel-app#17]
currently in dsPlug branch https://github.com/grafana/gel-app/blob/dsPlug/Makefile

Has some inconsistencies across platforms / calls - some currently N/A stuff re docker.

Will probably get merged still needing cleanup.

**Comment by aknuds1** [comment]
I presume we can close this @kylebrandt?

**Comment by kylebrandt** [comment]
fixed via switching to Mage, thank you @aknuds1 !
